---
# Kubernetes configuration
kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"
k8s_wait_timeout: 600
k8s_api_retries: 150
k8s_api_delay: 2

# Package versions
helm_version: latest
k3s_version: latest
