---
galaxy_info:
  author: Nuno Fernandes
  description: Static network configuration for Raspberry Pi
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - network
    - networking

dependencies: []

collections:
  - community.general
