apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: "1.92.5"
      helm:
        valueFiles:
          - $values/gitops/apps/tailscale/values.yaml
    - repoURL: https://github.com/nunoferna/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/nunoferna/homelab.git
      targetRevision: main
      path: gitops/apps/tailscale/config
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
