# Tailscale Kubernetes operator values.

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "tailscale"
  vault.hashicorp.com/agent-inject-secret-operator-oauth: "secret/data/tailscale"
  vault.hashicorp.com/agent-inject-template-operator-oauth: |
    {{ `{{- with secret "secret/data/tailscale" -}}` }}
    client_id: "{{ `{{ .Data.data.client_id }}` }}"
    client_secret: "{{ `{{ .Data.data.client_secret }}` }}"
    {{ `{{- end -}}` }}
  vault.hashicorp.com/agent-pre-populate-only: "true"
