apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nunoferna/homelab.git
    targetRevision: HEAD
    path: gitops/infrastructure
    directory:
      recurse: true
      include: "**/application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
