installCRDs: true

replicaCount: 1

webhook:
  timeoutSeconds: 10

cainjector:
  enabled: true

config:
  apiVersion: "controller.config.cert-manager.io/v1alpha1"
  enableGatewayAPI: true
  kind: "ControllerConfiguration"
