---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ common_apt_update_cache_valid_time }}"
  tags: packages
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    state: present
    autoremove: true
    autoclean: true
  tags: packages
  become: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_reboot_required
  tags: packages

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: common_reboot_required.stat.exists
  tags: packages

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  tags: packages
