apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policies
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  homelab-writer.hcl: |
    path "secret/data/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "secret/metadata/*" {
      capabilities = ["list", "read"]
    }
  
  homelab-reader.hcl: |
    path "secret/data/*" {
      capabilities = ["read", "list"]
    }
