---

galaxy_info:
  author: Nuno Fernandes
  description: Kubernetes cluster health verification
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - verification

dependencies:
  - role: k3s
  - role: cilium
