---

- name: Include Gateway API installation tasks
  ansible.builtin.include_tasks: gateway_api.yml
  tags: [cilium, gateway_api]

- name: Include Cilium installation tasks
  ansible.builtin.include_tasks: install.yml
  tags: [cilium, install]

- name: Include Cilium verification tasks
  ansible.builtin.include_tasks: verify.yml
  tags: [cilium, verify]
