global:
  domain: argocd.home.lab

configs:
  params:
    server.insecure: true

server:
  httproute:
    enabled: true
    parentRefs:
      - name: homelab-gateway
        namespace: gateway
    hostnames:
      - argocd.home.lab
