---
galaxy_info:
  author: Your Name
  description: Cilium CNI with Gateway API support for Kubernetes
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - cilium
    - networking
    - cni
    - gatewayapi

dependencies:
  - role: k3s
