---

galaxy_info:
  author: Nuno Fernandes
  description: ArgoCD GitOps continuous delivery tool
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - argocd
    - gitops

dependencies:
  - role: k3s
