---

galaxy_info:
  author: Nuno Fernandes
  description: Helm package manager installation
  company: NOF Homelab
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - helm

dependencies:
  - role: common
