apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/nunoferna/homelab.git
    targetRevision: main
    path: gitops/infrastructure/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
