apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab
  namespace: ingress
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.1.240
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.home.lab"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.home.lab"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: homelab-gateway-tls
      allowedRoutes:
        namespaces:
          from: All
