apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab
  namespace: ingress
spec:
  gatewayClassName: cilium
  # Reserve a specific LAN IP for this Gateway so it doesn't consume the
  # Pi-hole DNS IP (192.168.1.240).
  addresses:
    - type: IPAddress
      value: 192.168.1.241
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
