apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-to-https
  namespace: ingress
spec:
  parentRefs:
    - name: homelab
      namespace: ingress
      sectionName: http
  hostnames:
    - "*.home.lab"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
