---

galaxy_info:
  author: Nuno Fernandes
  description: HashiCorp Vault initialization and configuration
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - vault
    - secrets
    - security

dependencies: []
