apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lan-default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  blocks:
    - start: 192.168.1.1
      stop: 192.168.1.1
